### ISSUE TITLE
No tests?

### ISSUE THREAD

**Issue by bootstraponline** [Backblaze/JavaReedSolomon#1]
>  * This table was generated by java_tables.py, and the
>  * unit tests check it against the Java implementation.
> https://github.com/Backblaze/JavaReedSolomon/blob/master/com/backblaze/erasure/Galois.java#L56

It looks like there are no tests?

**Comment by bwbeach** [comment]
D'oh!  Missed those when I copied the code from the Backblaze source tree.

**Comment by bootstraponline** [comment]
Thanks!
