### ISSUE TITLE
Simple build system to build jar & run tests would be nice

### ISSUE THREAD

**Issue by bootstraponline** [Backblaze/JavaReedSolomon#2]
Is the idea to just copy and paste the source files directly instead of using a build system like gradle?

**Comment by bwbeach** [comment]
Gradle would be an excellent plan.  I'll add a gradle build file.

**Comment by bwbeach** [comment]
Just pushed.  I had been working on one after adding the test files.  I'm new to gradle, so let me know if there's a better way to do it.

**Comment by bootstraponline** [comment]
cool! I was able to successfully run `gradle jar` and `gradle test`. `build.gradle` looks good to me.

I think it'd be nice to:
- update the readme to mention the gradle commands for building/running tests
- setup Travis CI to automatically run the tests so people don't send pull requests that break the project

If PRs won't be accepted then it's fine to skip travis and just state that in the readme.

**Comment by bwbeach** [comment]
Added a quick mention of Gradle.  I'll think about Travis CI, especially if the change volume gets high.

**Comment by bootstraponline** [comment]
sounds good.
