### ISSUE TITLE
SSE3 Parallel Galois Multiplication

### ISSUE THREAD

**Issue by klauspost** [Backblaze/JavaReedSolomon#4]
(This is not an issue with the java implementation, but something you might find interesting, if you don't feel free to close the issue)

Since I may eventually do an assembler version of the main loop, I was researching if there was anything out there, and I found this: [Screaming Fast Galois Field Arithmetic](http://www.snia.org/sites/default/files2/SDC2013/presentations/NewThinking/EthanMiller_Screaming_Fast_Galois_Field%20Arithmetic_SIMD%20Instructions.pdf), which can do *constant* multiplications using two 16 bytes tables, which is perfect for SSE3. [[their implementation]](http://jerasure.org/jerasure/gf-complete/tree/master)

This requires the main loop to be slightly different (in Go)
```Go
	// output should be cleared, or first iRow loop should overwrite
	for c := 0; c < r.DataShards; c++ {
		in := inputs[c]
		for iRow := 0; iRow < outputCount; iRow++ {
			m := matrixRows[iRow][c]
			o := outputs[iRow]
			for iByte := 0; iByte < byteCount; iByte++ {
				o[iByte] ^= galMultiply(m, in[iByte])
			}
		}
	}
```
Now the one value (m) is a constant in the entire inner loop, so I should be able to do the multiplication with the byte[256][16] table, which only requires two look-ups for the entire inner loop.

I have generated the tables needed, and I will begin writing the assembler when I get a bit more time.

**Comment by klauspost** [comment]
Also, modifying the main loop like this also reduces the table size back to 256 bytes for the multiplication lookup i described in #3 .

**Comment by klauspost** [comment]
Using the modified main loop gives me a very significant speedup, especially on big shard sizes:
```
benchmark                       old MB/s     new MB/s     speedup
BenchmarkEncode10x2x10000       182.29       308.59       1.69x
BenchmarkEncode100x20x10000     14.41        30.29        2.10x
BenchmarkEncode17x3x1M          38.52        196.43       5.10x
BenchmarkEncode10x4x16M         23.78        148.58       6.25x
```

**Comment by bwbeach** [comment]
Nice work.  I like the way you've restructured the loop.

Because we're using Java at Backblaze, we don't have the option of using the SIMD instructions for parallel multiplication, but I'm glad that's working for you.

**Comment by bwbeach** [comment]
In the README, I added a link to the paper on using SIMD for the Galois multiplication.

What kind of machine are you using for your benchmarks?  We're getting 149MB/s with the Java code on a Xeon E5-1620 v2, clocked at 3.70GHz.

**Comment by klauspost** [comment]
It is a desktop  Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz.

Note that this is with no SIMD at the moment, just the re-ordered main loop and using the new lookup table, but looking up the 256byte sub-table outside the inner loop. You should be able to get at least a 2x speedup in java with the same technique.

I don't know the data size of your 149MB/s, but this is the throughput I get with each shard being 16MB and 17+3 shards as you describe in your article. This is the numbers for 1/2/4/8 threads used:
```
BenchmarkEncode17x3x16M	      10	1422781370 ns/op	 200.46 MB/s
BenchmarkEncode17x3x16M-2	      20	 787945065 ns/op	 361.97 MB/s
BenchmarkEncode17x3x16M-4	      30	 491594783 ns/op	 580.18 MB/s
BenchmarkEncode17x3x16M-8	      30	 396522680 ns/op	 719.28 MB/s
```

**Comment by klauspost** [comment]
... and the numbers with SSE3:
```
BenchmarkEncode17x3x16M	         100	 157539011 ns/op	1810.43 MB/s
BenchmarkEncode17x3x16M-2	     200	  88885084 ns/op	3208.78 MB/s
BenchmarkEncode17x3x16M-4	     300	  56706576 ns/op	5029.62 MB/s
BenchmarkEncode17x3x16M-8	     300	  44259198 ns/op	6444.14 MB/s
```

**Comment by bwbeach** [comment]
Those are great performance numbers.  Thanks for sharing.

Closing, because this isn't applicable to the Java implementation.
